language: r
cache: packages

env:
  global:
    - secure: "EP0CjNa9E0+L9EOlQdDZhziI1lKCxvR2/RutOK/uhm35U2bXzE37dpTjsQL2ei8W5TcfQYugOC+ji/BeZouVbJrtykl/PxhHeDHl5hiOHl5EdcrgpivgcneKAGxQ12eQGV0qufjU5nwc+uwoCnObHWSUuSEvHPiCNqghtyqZaQgHt5CxJY4YeEZo+u4p0acTFgbBbJWa3mO1FhkG6vQMesemmYw4Ho8LBxwZHTkgmz6kQjkUnqOISvw6QfycLkvbZKTEiXAjGAsRo6mMY6gyf/C2phIvLisG45J7QudKWksnimBwlMbb9kTDD/pLiD6CREJo1pjdWF6PHJmrGJXJ8GMZ9PMBQ2INCQZ/Cd0ZiujLnYdXksL/eAq4R8G+TKpe+/b7zTRVXetD0rkD0/wflphFQp4mni6NOb0vRV85GbPICMRP9MwFWOT0o423DzQIny7KG0BtUOuVqX1RqyPdj/xsswPX44mRJAT9ySZzjcvvYbNJ5M5w2BCmIxFZJBmCarcBzSpM/VLqxyEl/KvE0gUY2dVxS5sLoTkCoMRcjzd0OqojDgs3I5BgHkyzLQI696ufthdOdo2FprJtYAyV0pYQX1BIcRkCqVUERV8p//KBC3VDUXgZ0WRobCLMK/KVYVpAYNwboDvZuMGnppXfa4m8ELU+t4AA2PFRtX5AQbo="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
