language: r
cache: packages

env:
  global:
    - ENCRYPTION_LABEL: "e5dad7a5dcf1"
    - COMMIT_AUTHOR_EMAIL: "fbiomadeira@gmail.com"

  before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
